config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.searchkit:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.searchkit
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-sepia-wrasse.sh
        container: qc.acc_homey-amaranth-gar
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-brown-tiger.sh
        container: qc.doc_hasty-gamboge-pinscher
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-peach-cattle.sh
        container: qc.doc_freaky-heliotrope-termite
      github.com/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-persimmon-hedgehog.sh
        container: qc.doc_boozy-peach-angelfish
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-champagne-kingfisher.sh
        container: qc.lic_crappy-zucchini-coati
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-brown-buffalo.sh
        container: qc.met_thirsty-viridian-albatross
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lemon-loon.sh
        container: qc.sty_wimpy-orange-markhor
      github.com/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gold-mule.sh
        container: qc.sty_whiny-olivine-starfish
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-indigo-fly.sh
        container: qc.ver_nerdy-turquoise-bombay
timeout: 5400
