config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.searchkit:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.searchkit
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cardinal-greyhound.sh
        container: qc.acc_snappy-rust-spitz
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bistre-blue.sh
        container: qc.doc_leaky-rust-abyssinian
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lemon-cow.sh
        container: qc.doc_trippy-goldenrod-akita
      github.com/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lime-shrimp.sh
        container: qc.doc_snazzy-orchid-tang
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-myrtle-dunker.sh
        container: qc.lic_skimpy-heliotrope-cassowary
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-champagne-seal.sh
        container: qc.met_baggy-periwinkle-rhinoceros
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-magenta-bordeaux.sh
        container: qc.sty_shaggy-green-hornet
      github.com/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-mustard-eleuth.sh
        container: qc.sty_shaggy-russet-dollar
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-zucchini-deer.sh
        container: qc.ver_crabby-bistre-moth
timeout: 5400
