config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.searchkit:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.searchkit
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-rose-bandicoot.sh
        container: qc.acc_clammy-orange-eagle
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-azure-hound.sh
        container: qc.doc_surly-cerulean-mist
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aqua-impala.sh
        container: qc.doc_paltry-persimmon-penguin
      github.com/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-eggplant-warthog.sh
        container: qc.doc_sickly-lavender-drever
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cinnabar-affenpinscher.sh
        container: qc.lic_squirrely-periwinkle-alligator
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-gold-akbash.sh
        container: qc.met_clammy-linen-coyote
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-grey-bongo.sh
        container: qc.sty_muggy-dandelion-numbat
      github.com/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amaranth-opossum.sh
        container: qc.sty_wheezy-plum-octopus
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-platinum-millipede.sh
        container: qc.ver_flabby-teal-tarsier
timeout: 5400
